# Copyright 2019 IBM Corp.

# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 

#   http://www.apache.org/licenses/LICENSE-2.0 

# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License.

language: go

go:
  - 1.11.5
sudo: required
services:
  - docker
env:
  - PKG_VERSION=0.1.0

before_install:
  - echo "Setting project environment variable."
  - |
    export TRAVIS_REPO_OWNER=${TRAVIS_REPO_SLUG%/*}
    export TRAVIS_REPO_NAME=${TRAVIS_REPO_SLUG#*/}

install:
  - echo "Downloading images and tools."
  - |
    docker pull ipfsfb/ipfs-peer:$PKG_VERSION
    cd $GOPATH/src/github.com/$TRAVIS_REPO_OWNER/$TRAVIS_REPO_NAME
    make swarmkeygen ipfs

before_script:
  - echo "Setting project environment path."
  - | 
    export IPFS_PATH=/var/ipfsfb
    sudo chmod a+w $IPFS_PATH

script:
  - echo "Initializing profile and generating swarm key."
  - |
    ipfs init --profile=default-networking
    ipfs bootstrap rm --all
    TRAVIS_IPFS_ADDR=$(ipfs id -f='<addrs>' | tail -n 1)
    docker run -it --name peer0 -p 4001:4001 -p 5001:5001 -p 8080:8080 -p 8081:8081 ipfsfb/ipfs-peer:$PKG_VERSION \
    /bin/bash -c "ipfs init --profile=default-networking && ipfs bootstrap rm --all && ipfs bootstrap add $TRAVIS_IPFS_ADDR"
    swarmkeygen generate > $IPFS_PATH/swarm.key
    docker cp -a $IPFS_PATH/swarm.key peer0:/var/ipfsfb

after_failure:
  - docker logs peer0

notifications:
  email: false
