language: go

go:
  - latest
sudo: required
services:
  - docker
env:
  - REPO_NAME=ipfsfb
  - BASE_IMAGE_NAME=ipfs-node
  - PEER_DOCKER_TAG=peer
  - SERVER_DOCER_TAG=server

before_install:
  - echo "Setting project environment variable."
  - |
    export TRAVIS_REPO_OWNER=${TRAVIS_REPO_SLUG%/*}
    export TRAVIS_REPO_NAME=${TRAVIS_REPO_SLUG#*/}

install:
  - echo "Downloading images and tools."
  - |
    cd $GOPATH/src/github.com/$TRAVIS_REPO_OWNER/$TRAVIS_REPO_NAME
    make ipfs swarmkeygen
    chmod +x samples/simple-network/scripts/bootstrap.sh
    sudo ./samples/simple-network/scripts/bootstrap.sh latest -b -t

before_script:
  - echo "Setting project environment path."
  - |
    export IPFS_PATH=/var/ipfsfb
    sudo mkdir -p $IPFS_PATH
    sudo chmod a+w $IPFS_PATH

script:
  - echo "Testing function for each command line tools."
  - |
    docker run -it --name peer0 -p 4001:4001 -p 5001:5001 -p 8080:8080 -p 8081:8081 $REPO_NAME/$BASE_IMAGE_NAME:$PEER_DOCKER_TAG \
    /bin/bash -c "ipfs init --profile=default-networking && ipfs bootstrap rm --all && ipfs id -f='<addrs>'" >& peer0.log
    docker run -it --name server0 -p 4001:4001 -p 5001:5001 -p 8080:8080 -p 8081:8081 $REPO_NAME/$BASE_IMAGE_NAME:$SERVER_DOCER_TAG \
    /bin/bash -c "ipfs init --profile=server && ipfs bootstrap rm --all && ipfs id -f='<addrs>'" >& server0.log
    ipfs init --profile=default-networking
    ipfs bootstrap rm --all
    TRAVIS_IPFS_ADDR=$(ipfs id -f='<addrs>')
    echo $TRAVIS_IPFS_ADDR
    swarmkeygen generate > $IPFS_PATH/swarm.key
    cat $IPFS_PATH/swarm.key

after_failure:
  - echo "Viewing behave container log files."
  - |
    cat peer0.log
    cat server0.log

notifications:
  email: false
