language: go

go:
  - 1.11.x
sudo: required
services:
  - docker
env:


before_install:


install:


before_script:


script:


notifications:
  email: false
    # recipients:
    #   - hengmzh@cn.ibm.com
    # on_success: never
    # on_failure: always
  